// STUB. In the full deployment this file is GENERATED by
// scripts/extract-objectives.ts from the CCAR-P exam-guide PDF. The guide text is
// not redistributed here; see ./stub.ts and the README.
import { stubObjectives } from "./stub";

const OBJECTIVES = stubObjectives("CCAR-P");

export default OBJECTIVES;
